name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: containerbase/internal-tools/setup@9e2c008ec1b3662cb83d8ccdf68b2f0168c7f5d9 # v4.5.9
        with:
          save-cache: true

      - run: pnpm lint

  test:
    needs:
      - lint

    strategy:
      matrix:
        os:
          - ubuntu
          - macos
          - windows
        node:
          - 22
        include:
          # too slow and too many tests to run them on all os
          - os: ubuntu
            node: 24
          - os: ubuntu
            node: 25

    runs-on: ${{ matrix.os }}-latest

    name: test-${{ matrix.os }}-${{ matrix.node }}

    steps:
      - uses: containerbase/internal-tools/setup@9e2c008ec1b3662cb83d8ccdf68b2f0168c7f5d9 # v4.5.9
        with:
          save-cache: true
          node-version: ${{ matrix.node }}

      - run: pnpm build
      - run: pnpm jest

  # Catch-all required check for test matrix
  success:
    needs:
      - lint
      - test
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    if: always()
    steps:
      - name: Fail for failed or skipped test tests
        if: |
          needs.test.result == 'failure' ||
          needs.test.result == 'skipped'
        run: exit 1
