name: Release

on:
  release:
    types: [published]

jobs:
  release:
    environment: release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: ${{ github.event.release.target_commitish }}

      - uses: containerbase/internal-tools/setup@9e2c008ec1b3662cb83d8ccdf68b2f0168c7f5d9 # v4.5.9
        with:
          checkout: false

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

      - name: Publish
        run: pnpm publish --access public
