name: Trunk

on:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu
          - macos
          - windows
        node:
          - 22
        include:
          # too slow and too many tests to run them on all os
          - os: ubuntu
            node: 24
          - os: ubuntu
            node: 25

    runs-on: ${{ matrix.os }}-latest

    name: test-${{ matrix.os }}-${{ matrix.node }}

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn --frozen-lockfile --no-progress
      - name: Build
        run: yarn -s build
      - name: Test
        run: yarn -s test
